name: After_long_workflow

on: 
  workflow_dispatch: 


jobs:
  terrascanning :
    name: terraform scanning 
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
         scan-type: 'fs'
         scan-ref: '.'
 
  terraforminit:
    name: terraform init 
    runs-on: self-hosted

    steps:

     - name: checkout
       uses: actions/checkout@v4

     - name: terraform init
       run: terraform -chdir=MODULE init
  
     - name: terraform validate
       run: terraform -chdir=MODULE validate
  
     - name: terraform plan
       run: terraform -chdir=MODULE plan

     - name: terraform apply
       run: terraform -chdir=MODULE apply -auto-approve

        

        
