name: After_long_workflow

on: 
  workflow_dispatch: 


jobs:
  terraforminit :
    name: terraforminit
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: terraforminit
        run: terraform -chdir=MODULE init

      - name: terraformvalidate
        run: terraform -chdir=MODULE validate
